# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MahjongKitchen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MahjongKitchen
  pod "Purchases"

  target 'MahjongKitchenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MahjongKitchenUITests' do
    # Pods for testing
  end

end
